import { createHash, randomBytes } from 'node:crypto';

/**
 * A human readable, unique identifier for a movement of money, generated by the
 * service. Distinct from the client's idempotency key: the key is an input the
 * caller chooses, the reference is an output this service owns.
 */
export function generateReference(prefix: 'TRF' | 'CRD'): string {
  return `${prefix}_${Date.now().toString(36).toUpperCase()}_${randomBytes(5).toString('hex').toUpperCase()}`;
}

/**
 * A hash of the request an idempotency key was first used with.
 *
 * If the same key arrives carrying a different payload, that is a client bug.
 * Returning the original result would report that one transfer succeeded when a
 * different one is what actually happened, so the fingerprint lets the mismatch
 * be rejected instead.
 */
export function fingerprintRequest(parts: Record<string, string | number>): string {
  const canonical = Object.keys(parts)
    .sort()
    .map((key) => `${key}=${parts[key]}`)
    .join('&');

  return createHash('sha256').update(canonical).digest('hex');
}
